#!/usr/bin/python3

import sys
from PIL import Image


def main(image_name):
    image = Image.open(image_name)
    width = image.width
    height = image.height
    square_side = min(width, height)
    squared_image = image.crop((0, 200, square_side, square_side))
    resized_squared_image = squared_image.resize((150, 150))
    resized_squared_image.save("test.jpg")


if __name__ == "__main__":
    image_name = sys.argv[1]
    main(image_name)
